---
version: "2.0"

setup:
  ruby: 3.3.8
  bundler: true
commands:
  test:
    summary: Run the project's specs
    command: |
      bundle exec appraisal install
      bundle exec appraisal rspec spec/
