---
name: CI

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.0
          - 3.1
          - 3.2
        # active-record-version:
        #   - 6.1.0
        #   - 7.0.0
        #   - 7.1.0
        # exclude:
        #   - ruby-version: 3.2
        #     active-record-version: 6.0.0
        #   - ruby-version: 3.2
        #     active-record-version: 6.1.0
        #   - ruby-version: 3.2
        #     active-record-version: 7.0.0
        #   - ruby-version: 3.1
        #     active-record-version: 6.0.0
        #   - ruby-version: 3.1
        #     active-record-version: 6.1.0
        #   - ruby-version: 3.0
        #     active-record-version: 6.0.0
    # env:
    #   ACTIVE_RECORD_VERSION: "${{ matrix.active-record-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - name: Run tests
        run: bundle exec appraisal rspec --format documentation
